version: 0.0
os: linux
files:
  - source:  /build/libs/*.jar
    destination: /home/ec2-user/build/
    overwrite: yes

hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user